### ISSUE TITLE
joaquinReitu | Lesson 2

### ISSUE THREAD

**Issue by martin5211** [martin5211/learn-node-js#10]
https://github.com/martin5211/learn-node-js/blob/a429703c493216c6c6a466d17c3236cf51f6c8e6/lesson_2/ejercicio/LESSON_2_JoaquinReitu/app.js#L32

- It should be `file.log` instead of `fs.log`

- The file log.json saves `[object Object]` instead of valid JSON.

**Comment by JoaquinR1** [comment]
Corregido

**Comment by martin5211** [comment]
I found some issues:

- You're storing the log with this format: ["msg1", "msg2"]. It should be: 

```
[
      {
        seesionId: 'UUID',
        msg: 'msg1'
      },
      {
        seesionId: 'UUID',
        msg: 'msg2'
      },
 ]
```

https://github.com/martin5211/learn-node-js/blob/6e91647e095fc57558e6fb3f8168bd48df17a9eb/lesson_2/ejercicio/LESSON_2_JoaquinReitu/app.js#L28

- You can send only one response per request otherwise you will get `Headers already sent` error. Please remove `res.send('Finished...');` because it isn't needed at all

**Comment by JoaquinR1** [comment]
Corregido

**Comment by martin5211** [comment]
The exercise you've created stores always the same message. What it was requested is to send the message through HTTP. Remains to be created a POST endpoint on which it can receive the message through the body

**Comment by JoaquinR1** [comment]
Corregido

**Comment by martin5211** [comment]
Looks good now. Closing issue.
