### ISSUE TITLE
Nico Tosolini | Lesson 3

### ISSUE THREAD

**Issue by martin5211** [martin5211/learn-node-js#21]
- Usually, when we create a web service, the responses should be returned always in JSON format and not in HTML. You can create an app to return the messages in friendly HTML and to be accessed into the browser, but the core of the services e.g. the refresh and clean operations must return the response in JSON format.

- The HTTP method to clean the promotions should be DELETE and not GET.

- The JSON response should have the following structure:
```
{
  "promociones" : [
    {
      "nombre": "Descuentos del 10% con pagos en efectivo."
    }, ...
  ]  
}
```
The document should be stored into Redis with the same structure

**Comment by TosoliniNico** [comment]
Okay, I think I did all the correction that was required, if something else is missing I would like you to let me know.
Regards

**Comment by martin5211** [comment]
Looks good now. Just to advice, if you remove the start property inside scripts on the package.json, the application won't start. Closing issue.
