### ISSUE TITLE
martinpuyo | Lesson 1

### ISSUE THREAD

**Issue by martin5211** [martin5211/learn-node-js#6]
https://github.com/martin5211/learn-node-js/blob/274298911ae1b163166c8494492c4386e796ea26/lesson_1/ejercicio/app.js#L4

- As it was seen in the other reviews you can use simply `process.argv` instead of the external module `yargs`. (https://nodejs.org/docs/latest/api/process.html#process_process_argv)

https://github.com/martin5211/learn-node-js/blob/274298911ae1b163166c8494492c4386e796ea26/lesson_1/ejercicio/app.js#L5

- To comply with the exercise in the second lesson, the log output format should be changed to a valid JSON. 

https://github.com/martin5211/learn-node-js/blob/274298911ae1b163166c8494492c4386e796ea26/lesson_1/ejercicio/app.js#L7

- `fs.writeFile` isn't needed as `fs.appendFile` will create a file if it doesn't exist. (https://nodejs.org/api/fs.html#fs_fs_appendfile_path_data_options_callback)

https://github.com/martin5211/learn-node-js/blob/274298911ae1b163166c8494492c4386e796ea26/lesson_1/ejercicio/app.js#L14

- The appender should be moved to an external module so it can be reused. It's single responsibility, the first principle of SOLID.

**Comment by martinpuyo** [comment]
Corregido

**Comment by martin5211** [comment]
Looks good! Keep advancing in the exercises
